### ISSUE TITLE
Pouchdb client usage

### ISSUE THREAD

**Issue by arnoutaertgeerts** [colinskow/superlogin#1]
First off, this really looks like a great solution and the first library I have seen to support all thèse features. Nice job!

Do you have an idea how this could work with pouchdb in the browser? Maybe as a better replacement to [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication)?

**Comment by colinskow** [comment]
The difference between SuperLogin and pouchdb-authentication, is that SuperLogin creates sessions with throw-away credentials so you have more control. When you log out of the session, those credentials no longer work. It also coordinates those credentials across multiple databases that you have permissions for.

I am finishing up a demo app that shows exactly how to coordinate the SuperLogin server with PouchDB in the browser. After you login, the session information returned contains a field called `userDBs`. Simply pass the URLs provided into the PouchDB constructor.

**Comment by arnoutaertgeerts** [comment]
@colinskow Thanks, sounds awesome!

**Comment by colinskow** [comment]
The [SuperLogin Demo](https://superlogin-demo.herokuapp.com) is now LIVE! Source code [here](https://github.com/colinskow/superlogin-demo).
