### ISSUE TITLE
Login with username or E-mail?

### ISSUE THREAD

**Issue by peteruithoven** [colinskow/superlogin#107]
Superlogin already supports configuring whether the user logs in through username or E-mail, but there are cases where allowing both is useful. Much like Twitter and Facebook for example; 
- Twitter allows login with Phone, E-mail or username
- Facebook allows login with E-mail or phone

In our case we use the username to identify users, to give them a name in the community, but we also think most users will remember their E-mail more easily. In the future we'd like to improve the support for usage in schools, where we can't ask for an E-mail address. 

So I'd like to simple ask the user:
- Username or E-mail?
- Password?

**Comment by MichalZak** [comment]
I agree, also would like to see this feature

**Comment by peteruithoven** [comment]
Later on we discovered that this is already possible, unless the `emailUsername` config option is enabled. Looks like a regular expression is used to determine whether a username of E-mail was used. 
https://github.com/colinskow/superlogin/blob/master/lib/user.js#L234-L236
So we where simple able to change `Username` to `Username or E-mail`. 
Which was of course a very nice surprise.
