### ISSUE TITLE
Is Couchdb 2.0 supported?

### ISSUE THREAD

**Issue by chaitanya9186** [colinskow/superlogin#109]

**Comment by EuAndreh** [comment]
As far as I've used it, it is totally compatible. Since there were no big changes to the authentication/authorization API in CouchDB 2.0, this should really work indeed. SuperLogin behaved the same in CouchDB 1.6.x, CouchDB 2.0.0 and Cloudant.

Have you had any issues?

**Comment by colinskow** [comment]
Cloudant is supported which uses a very similar API to CouchDB 2.0. If you find something specific which doesn't work please file an issue.

**Comment by chaitanya9186** [comment]
Thank you.
