### ISSUE TITLE
Authenticate against local pouchDB instance

### ISSUE THREAD

**Issue by markdturner** [colinskow/superlogin#126]
I'm having difficulty following the API documentation for using superlogin against pouch instead of couch. The API documentation has the following line for the superlogin constructor:

> userDB: This is the database that SuperLogin uses to keep track of users, distinct from CouchDB's _users database. You can pass in a PouchDB instance here or otherwise specify your database name in the config under dbServer.userDB

So I use the API like so (where app.localUsersDB is a node pouchDB instance).

`app.superlogin = new SuperLogin(config, passport, app.localUsersDB);`

This works no problem when connected to the internet but when offline users cannot login. My config object has the details for the remote server, and when the login fails I can see that superlogin is trying to contact that remote server instead of validating against the local pouch instance.

Is there any example code for using pouch instead? 

Let me know if you need any more code snippets or config details.

Thanks!

**Comment by markdturner** [comment]
I think the crux of the problem is not knowing what to set as the dbServer.host property in the config. I'm using a local instance of Pouch set up like so:

`new PouchDB('./data/' + config.dbServer.userDB);`

The documentation seems to suggest that passing this instance of Pouch into the Superlogin constructor is fine, let the login method doesn't work with having a host set. If I leave it blank it errors with a message of 

`Error: getaddrinfo ENOTFOUND undefined undefined:80. `

If I change it to be a URL to my remote database I ultimately want to sync with. then it works - but only when I'm online. The whole purpose of using this local instance is to enable offline login (providing the databases have synced at least once previously).

**Comment by webnoob** [comment]
Did you manage to get anywhere with this? I'm thinking of using superlogin but I need to be able to log in offline with pouchDb.

**Comment by webnoob** [comment]
Something I noticed from the docs, the 4th param in the C'tor accepts the couchDb auth database. It also says you can pass the pouch instance as that param. 

`couchAuthDB: This should point to your CouchDB _users database or something else if you just want to test. Specify in config or pass in a PouchDB object here.`

If you pass your pouchDB instance as the fourth param, does that sort it? 

Note: I give this advice having never used superlogin but thought it worth looking in to.

**Comment by micky2be** [comment]
Without talking about the fact it would be highly insecure you won't be able to do it.
How the session/login system works is a built in system in CouchDB.

**Comment by markdturner** [comment]
I ended up swapping Pouch for a full blown local Couch installation and then handling the syncing between the two. I was attempting to get pouch working on the server with Node because the web app needs to be served from a Raspberry Pi, so I was trying to go as lightweight as possible; but in the end, I just had to put Couch on the Pi.

The 'local' Couch installation running on the Pi allows users to login (so long as they have previously been synced down from the central server) even if the Pi cannot connect to the outside world.

**Comment by webnoob** [comment]
I've gone down a different route myself. I want to ensure my users come online every 24 hours so have set the timeout to 24hours on the token. This allows me to make sure they've paid etc and also means I don't need to auth against the pouch instance.

Just posting this here in case anyone finds the thread and needs some inspiration.
