### ISSUE TITLE
Using existing users from _user

### ISSUE THREAD

**Issue by ander2** [colinskow/superlogin#13]
I'm testing **superlogin** module and I'm able to create new users into the **dbServer.userDB** database and login with them.

Now I would like to login with an user from **dbServer.couchAuthDB**, without registering that user with **superlogin** with no success.

Is it supported to login with users from  **_users** ?

**Comment by ronyrun** [comment]
Hi, I think you can't. Superlogin use its own users DB.

**Comment by ander2** [comment]
So then, why is **dbServer.couchAuthDB** option available?

Which is it's purpose? I'm little bit confused with this.

**Comment by ronyrun** [comment]
It's because there is a difference between coudDB and Cloudant.

**Comment by colinskow** [comment]
@ander2 SuperLogin does not authenticate users directly with CouchDB, it only authenticates a user's sessions. When a user authenticates with SuperLogin, a (random) session key and password are generated. These credentials are temporary and can be used to authenticate with both your Node/Express API and CouchDB. The reason for this is that it is bad security to store a username and password (which may be the same on other sites) on a device and transmit it to the server on every request.

If you want normal simple CouchDB login, then SuperLogin is probably overkill for your needs. I created SuperLogin to increase the level of security and enable CouchDB and Node APIs to use the same authentication scheme.

**Comment by ybian** [comment]
@colinskow It is a smart idea to authenticate users' sessions in _users table. I was very excited when I first found this project. It does the **exact** things I had in my mind with the **exact** technology stack for my current project. It saved me a lot of time. Big thanks to you!!

**Comment by tohagan** [comment]
@colinskow Ditto.  Very cool and just what I needed.   Lovin' it   :)  !
