### ISSUE TITLE
How to use addUserDB from the client

### ISSUE THREAD

**Issue by webnoob** [colinskow/superlogin#130]
I need the ability to be able to add a new user / allow access to a DB from the client. There are no routes for this by default so is there another way this can be achieved?

**Comment by chriseyhorn** [comment]
You need to setup a route that passes the information to the addUserDB call that can be called from the client side.  Check out https://github.com/colinskow/superlogin-demo project for example routes.

**Comment by webnoob** [comment]
Ok, thanks. I'll take a look and see.
