### ISSUE TITLE
Exception invoking removeExpiredKeys.

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/superlogin#138]
@colinskow : Please see this PR - https://github.com/colinskow/superlogin/pull/137. A context issue causes removeExpiredKeys to throw up an exception as `dbAuth.removeKeys` is not resolved.

This issue has been resolved in the PR, please verify and merge.

**Comment by peteruithoven** [comment]
Seeing that pull request has been merged this issue could probably be closed?

**Comment by SukantGujar** [comment]
Thanks for reminding me!
