### ISSUE TITLE
Testing report

### ISSUE THREAD

**Issue by tohagan** [colinskow/superlogin#14]
I've just run some very basic testing of your demo app with the following:

* Win7 Latest Chrome 46.0.2490.80 m - Works well.
* Android 4.4 - Works very well and live syncs ok
* iPhone Safari - Works well and live syncs ok

* Same with Firefox 41.02 and Firefox 42.0
   - Facebook Auth appears to work
  - Then nothing more displayed.
  - Does not sync with existing data from same FB account. 
  - Does not save data between session (so probably not syncing at all)
  
* Internet Explorer 11.0.9600.18059
     - shows login page but only displays title bar with header text - no login buttons or links.

**Comment by colinskow** [comment]
You must be referring to https://github.com/colinskow/superlogin-demo
Please copy and paste this issue there.
