### ISSUE TITLE
anonymous users

### ISSUE THREAD

**Issue by raymatos** [colinskow/superlogin#15]
Does superlogin have support for anonymous users?

**Comment by colinskow** [comment]
You can easily configure CouchDB and Cloudant to allow anonymous users. Please tell me about your use case and what exactly you would like SuperLogin to do.

**Comment by raymatos** [comment]
Mobile app - users can choose to either create an account or skip (anonymous).  User can at a later point choose to create an account.




I can handle it different ways within the app, but I rather not do a something like




If anonymous 

Save on device

Else 

Save on couch db 







I rather save everything to couch db and deal with migrating a user from anonymous to normal.









—

**Comment by colinskow** [comment]
Based on what you've said you want to do I think the simplest way is to simply use a `session_id` to keep track of your anonymous users which can be stored in a cookie. After the user has created an account, you can then add the `user_id` to all the anonymous records for that session. You can also manually add the `session_id` to the user record in SuperLogin.

I don't think there's any feature I can add to SuperLogin that will make this easier for you that would handle all possible use cases.

**Comment by colinskow** [comment]
I'm closing this. Feel free to re-open if anyone has any further ideas on anonymous users.
