### ISSUE TITLE
Shared database authorization not scalable?

### ISSUE THREAD

**Issue by peteruithoven** [colinskow/superlogin#152]
I'm trying to wrap my head around the security model that's used for shared databases. I understand it differs between plain CouchDB and Cloudant. 
## CouchDB
Creates a `_users` database and for every user it creates a document with a unique id and derived_key. This `_users` db is added besides superlogin's userDB (`sl_users` for example.)
This id is then added to `members.names` in the `_security` document of the shared database. 
More info: http://docs.couchdb.org/en/1.6.1/intro/security.html#authentication-database
## Cloudant
Creates an API key per user using `_api/v2/api_keys`. This key is then added to a `cloudant` object in the `_security` document of the shared database. In this `_security` document, per key, the [roles](https://console.ng.bluemix.net/docs/services/Cloudant/api/authorization.html#roles) are defined. 
More info: https://console.ng.bluemix.net/docs/services/Cloudant/api/authorization.html
(Cloudant also has support for the CouchDB _users model, although it doesn't (yet) hash the password. 

## Resulting in user specific permissions per database? 
This all seems to mean that in each shared database's `_security` document all the users are listed. This doesn't seem maintainable at all? What if I'd like to add another shared libary later on or want to change the rights of existing users? 
When I currently visit our Cloudant dashboard and go to the permissions page of a shared database my browser hangs, because it's having problems loading / rendering all the permissions. (because every user is listed).

## Why not role based?
CouchDB _users system also allow you to list members.roles and if I understand it correctly in the case of Cloudant API keys could be created per "role" and be shared with multiple users. 
More information on sharing API keys on Cloudant: https://dx13.co.uk/articles/2016/4/11/using-a-cloudant-api-key-with-multiple-cloudant-databases-and-accounts.html

The plain CouchDB _users roles model seems much easier in my opinion? (Although I'm not sure if superlogin can already handle the hashing of passwords on Cloudant.)
Having roles means that you end up with only a couple of roles per database, creating a very readable and maintainable `_security` document. 
What do you guys / girls think?

**Comment by colinskow** [comment]
With SuperLogin you can store an array of approved roles for each user. (Just edit the `roles` array in the `sl_users` doc for each user.) Authentication is session based, so each login generates a unique Cloudant API key or on CouchDB a random username/password. When the session logs out, access is removed for that key. When the session expires, SuperLogin automatically invalidates that key.

Sharing Cloudant API keys between users would definitely be bad security. You setup [traditional CouchDB authentication](https://docs.cloudant.com/authorization.html) on Cloudant if you like, but I like Cloudant's model much better.

Per-role instead of per-session `_security` is possible. Just make sure the user has the correct role in their `sl_users` doc and they should be able to access a shared database which has that role enabled.

**Comment by peteruithoven** [comment]
Thanks for the quick reply. I totally didn't get that it was session based. 

So per session a API key is generated which is added to all the databases listed in `userDBs.shared`? If we're just thinking about Cloudant and `userDBs.model.[somedatabasename].permissions` defines the permissions that session get's automatically for that database? Which is updates when a new session is started? Does a refresh result in a new session?

> With SuperLogin you can store an array of approved roles for each user. (Just edit the roles array in the sl_users doc for each user.)

You mean the roles each new user gets by default? You mean editing the roles array of each user doc in the `sl_users` database?

> Per-role instead of per-session _security is possible. Just make sure the user has the correct role in their sl_users doc

You mean in each user's doc in the `sl_users` database right?

How do you for example setup the `nobody` api key with the superlogin config?

**Comment by colinskow** [comment]
You are correct in most of your assumptions. A refresh leaves the session login and password intact, and simply extends the life.

One additional piece of advice I can give you is to run `superlogin.removeExpiredKeys()` on a scheduler (as often as practical for desired security) to remove all expired sessions from the `_security` docs of all your databases. This will keep them from getting too cluttered.

> How do you for example setup the nobody api key with the superlogin config?

I'm not sure what you mean by this.

**Comment by peteruithoven** [comment]
Thanks for the clarifications! 

I always assumed that removeExpiredKeys was for removing old sessions from user's databases. I will defiantly look into that, that's probably one of the biggest reasons we're having problems loading the Permissions pages. 

In regards to the `nobody` key / username, it's a way to determine the access of unauthenticated users.  Below is an example `_security` document, this contains a `nobody` key which has _reader permissions, this means that the database is publicly readable to unauthenticated users
``` json
{
    "cloudant": {
        "antsellseadespecteposene": [
            "_reader",
            "_writer",
            "_admin"
        ],
        "garbados": [
            "_reader",
            "_writer",
            "_admin"
        ],
        "nobody": [
            "_reader"
        ]
    }
}
```

> The special nobody user name applies for anyone or any application that tries to do tasks, but that did not authenticate with the system. In other words, the nobody user name applies to all unauthenticated connection attempts. For example, if an application attempts to read data from a database, but did not identify itself, the task can proceed only if the nobody user has the role _reader.

More info: https://console.ng.bluemix.net/docs/services/Cloudant/api/authorization.html#enabling-the-_users-database-with-cloudant

**Comment by peteruithoven** [comment]
> Per-role instead of per-session _security is possible. Just make sure the user has the correct role in their sl_users doc and they should be able to access a shared database which has that role enabled.

This would only be possible using the CouchDB system right? 

> You are correct in most of your assumptions. A refresh leaves the session login and password intact, and simply extends the life.

But what if I need to update the permissions? 

Using the Cloudant security model: What if I'd like to "upgrade" a user? Adding extra permissions for shared databases or adding a new shared database. Could I simply update the db using `addUserDB`, with other permissions? Would I first need to use `removeUserDB()? Does this automatically update the existing session API keys in databases? Or do I need to logout the user and have him login again? (I'm hoping that's not necessary) 

When using the Cloudant model, how does one add new shared databases or edit permissions to shared databases for all existing users? I'm assuming I'd need to go through all the user docs and update them using `addUserDB`? Kind of the same question as above, what's the best way to then update the session API keys in the databases?

**Comment by peteruithoven** [comment]
Also back to the subject of scalability for a moment. Superlogin currently seems to authorizes / deauthorizes databases per user. 
When running for example removeExpiredKeys it queries the userDocs for expired keys, collects those per user and then goes per user through all that user's databases to deauthorize the keys. But to deauthorize keys it needs to download the _security document, update it and then upload it again. So this happens amount of users * amount of personal databases. If I understand the code all these requests are basically started at the same time. This doesn't seem very scalable?  

I'm afraid it already fails in our production database, running `removeExpiredKeys()` goes through quite a lot of users / sessions, but not all and it then throws the following error:
```
(node:22227) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: read ECONNRESET
```
Could be a separate issue, but I'm assuming it's just to much to fast. 

A partial first fix might be to make sure these requests happen in series instead of parallel? Maybe like we use an `asyncIterator` in this code: https://github.com/colinskow/superlogin/issues/63#issuecomment-301041076

**Comment by peteruithoven** [comment]
I sort of answered those last questions myself and I've opened a separate issue on the scalability of removeExpiredKeys: https://github.com/colinskow/superlogin/issues/158
