### ISSUE TITLE
Help: Session not functioning

### ISSUE THREAD

**Issue by mrsideshowjack** [colinskow/superlogin#155]
Hi there, my users session doesn't work, i.e. they have to login upon refresh.
My app doesn't exactly standard implementation of superlogin, but as far as I can tell, I don't think  and i'm at a loss as to why the session isn't working.

front: Polymer
back: node/express w/ superlogin

* login/signup/logout all work perfectly
* It is hosted on Bluemix, basically an ibm version of Heroku, and I'm using the redis service in bluemix.
* The storage is on cloudant, and can see session storage information stored in each user
* I do get `Redis is ready` on server start

Am I missing something? I'm not using ng-superlogin, just what is in this repo.

**Comment by peteruithoven** [comment]
Superlogin-client should store the session in localStorage, you could you check it's there using: 
``` js
localStorage.getItem('superlogin.session')
```
You could then check whether that `token` is avaiable in redis. Looking at my code you should have an `token${thetoken}` item. For example using: 
```
#!/usr/bin/env node
// Inspired by Bash Redis client: https://github.com/crypt1d/redi.sh
const cli = require('cli')
const redis = require('redis');

const TOKEN_KEY_PREFIX = 'token';
const options = cli.parse({
  get: ['g', 'Get the variable specified by <name> and output it to stdout.', 'string'],
  // set: ['s', 'Set the variable specified by <name> with the input from stdin.', 'string'],
  // del: ['d', 'Delete the variable specified by <name>.', 'string']
});
// console.log('options: ', options);

const url = process.env.REDIS_URL;
if (!url) throw new Error('No REDIS_URL env found')
// console.log('url: ', url);

const redisClient = redis.createClient(url);
redisClient.on('error', function (err) {
  console.error('error: ' + err);
});
redisClient.on('connect', function () {
  // console.log('connected');
  for (operation in options) {
    const input = options[operation];
    if (!input) continue;
    const key = getKey(input);
    console.log(`${operation}: '${key}'`); 
    switch(operation) {
      case 'get':
        redisClient.get(key, (err, value) => {
          handleError(err);
          console.log(value);
          process.exit();
        });
        break;
    }
  }
});
function getKey(token) {
  return `${TOKEN_KEY_PREFIX}:${token}`;
}
function handleError(err) {
  if (err) {
    console.error('error: ' + err);
    process.exit(1);
  }
}
```
And then running that by calling it like:
```
node redis.js -g thetoken
```

**Comment by mrsideshowjack** [comment]
@peteruithoven Thank you for the reply

So the Superlogin-client is imported/ used with Typescript? So would using something like [typescript-compile](https://github.com/niutech/typescript-compile) work? just to import and configure superlogin-client.

Is that right?

**Comment by peteruithoven** [comment]
Oh wait, you're not using a front-end client (ng-superlogin / superlogin-client)? That would explain things. You need to store the session somewhere, superlogin doesn't work with Cookies. This is handled by superlogin-client. 
( I have no experience with Typescript. We're using es2015 (using babel). )

**Comment by mrsideshowjack** [comment]
Ok, thanks for your help, i'll try to get superlogin-client to work.

I wish there was a vanilla js or web components version of the front-end client, something I could use with HTML imports.

**Comment by peteruithoven** [comment]
superlogin-client is vanilla js? There is no framework (polymer / ng / react / ...) involved. 
If you use a package manager (npm / yarn / jspm) and a transpiler (babel, typescript) you can simply install and import it?

**Comment by mrsideshowjack** [comment]
I've never used a transpiler, and I'm not exactly sure how i would integrate one into my framework.

**Comment by peteruithoven** [comment]
I'm not sure either. Transpilation should be framework independent. I would recommend looking into Webpack2. Being able to install and import packages is a great benefit in general. 
Maybe this question is interesting: https://github.com/webpack/webpack/issues/547

**Comment by peteruithoven** [comment]
I think this issue could be closed? @mrsideshowjack didn't store the session yet on the client.
