### ISSUE TITLE
UserDB's Urls Host

### ISSUE THREAD

**Issue by baststar** [colinskow/superlogin#16]
Hi. superlogin is very nice!! I love it. Best solution i found so far! :-)
I found one issue when you use a local couchdb-instance on the server.
In lib/user.js at createSession you build the url for the UserDBs with the dbServer.host, which is for example localhost:5984. But on the client, for example with IonicFramework, you can't connect to http://tokenxyz:passwordxyz@localhost:5984/dbname. Instead of localhost there must be the IP of my server. This should be configurable in the config on the server.

**Comment by colinskow** [comment]
In your config under `dbServer` you can set `host` to the correct ip address and port. See the [sample config](https://github.com/colinskow/superlogin/blob/master/config.example.js) for more information.
