### ISSUE TITLE
html in Emails?

### ISSUE THREAD

**Issue by Simon-Laux** [colinskow/superlogin#161]
or any way to add email headers?

I'm asking, because i have html in my confirmation email and i would like to have it displayed properly.

Thanks in advance.

-simon

**Comment by Simon-Laux** [comment]
oh i dumbass, i found it: `format: 'text'` in the config

**Comment by Simon-Laux** [comment]
I want to ask 2 other questions belonging that topic:
- how can i specify the utf8 charset so that german chars like "ä" and Emoji´s could be displayed?
- which propertys of the user can i display an the emails? as example i would like to display the email of the user.

**Comment by peteruithoven** [comment]
I don't know about the chartset, but in regards to the data a template gets looking through the code it seems to get the request object and the user doc: 
https://github.com/colinskow/superlogin/blob/master/lib/user.js#L306
https://github.com/colinskow/superlogin/blob/master/lib/mailer.js#L20-L54

**Comment by Simon-Laux** [comment]
Ok I found the problem - I forget to save it in utf8
![utf8cov](https://cloud.githubusercontent.com/assets/18725968/26209054/0a15d0f4-3bec-11e7-8526-a1d36d4fd52d.png)
The email works now.

The email property seems to get deleted, so I can't use that one without modifying superlogin:
https://github.com/colinskow/superlogin/blob/master/lib/user.js#L272

**Comment by peteruithoven** [comment]
Good point, but looks like it's moved to `unverifiedEmail.email`?
