### ISSUE TITLE
[Question] I added another shared DB after some users registration.

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#17]
Hello, 

I added another shared DB after some users registration.
The access to the new Shared DB are generated with new users created after its creation.
But for previous Users, the access to this new Shared DB is not generated then they can't have access to it.
Is there a way to connect the previous created users to this new Shared DB  ?

t0 : I config a A-sharedDB.
t1 : Some users registered with an access to the A-sharedDB.
t2 : I config a B-sharedDB.
t3 : New users registrered with an acccess to the A-sharedDB and B-sharedDB.

but when t1 users deconnect and reconnect to superLogin they only get an access to the A-sharedDB and not to the B-sharedDB.

Ron

**Comment by ronyrun** [comment]
OK I think I found a solution, 

I did update the doc of users in the Users db and adding the new shared DB.

**Comment by colinskow** [comment]
See `superlogin.addUserDB` in the docs. This should configure all the permissions for you.

**Comment by ronyrun** [comment]
OK
