### ISSUE TITLE
Conditionally add multiple DBs to new users

### ISSUE THREAD

**Issue by christianmccormick** [colinskow/superlogin#18]
I want to add several user DBs when a particular type of user signs up. I can't do this with defaultDBs as I don't want create these DBs for every user account, only ones with a particular type. Here's my code:

````
var dbs = [
  'example',
  'dbs',
  'to',
  'add'
];

superlogin.on('signup', function(userDoc, provider) {
  if (userDoc.user_type === 'special') {
    dbs.forEach(function(db) {
      superlogin.addUserDB(userDoc._id, db).then(function(res) {
        console.log('Success: ' + res);
      }, function(err) {
        console.log('Error: ' + err);
      });
    });
  }
});
````

dbs is an array of the DB names that I want to create for a user with the user_type "special". The first DB gets created but the others all throw "Document update conflict" errors. I'm assuming that I'm using addUserDB incorrectly, but am stumped as to how. Any help would be appreciated! I've tried other approaches as well but nothing seems to work.

**Comment by colinskow** [comment]
You need to make sure `addUserDB` is finished before calling it again. 

```js
superlogin.on('signup', function(userDoc, provider) {
  var promises = Promise.resolve();
  if (userDoc.user_type === 'special') {
    dbs.forEach(function(db) {
      promises.then(function() {
        return superlogin.addUserDB(userDoc._id, db)
      });
    });
  }
});
```

**Comment by ronyrun** [comment]
:+1:

**Comment by christianmccormick** [comment]
Thanks @colinskow! Loving SuperLogin—exactly what I needed to manage users on Cloudant.

**Comment by colinskow** [comment]
@christianmccormick glad to hear that it is useful to others!!! I thought it would be a simple project but ended up spending a couple months practically full time with thousands of lines of code to get in all the logic I needed to handle multiple personal DBs (and test it).

Security can be one of the most time consuming aspects of building a web app, so I wrote SuperLogin to take that load off of other developers.
