### ISSUE TITLE
userModel is not extended correctly

### ISSUE THREAD

**Issue by raymatos** [colinskow/superlogin#19]
When extending the user model, nested arrays are not concatenated their positions are overwritten.

ie: 

```
var userModelConfig = {whitelist: ['1','2','3','4','5','6']}
var userModel = {whitelist: ['a','b','c']}

$.extend(true, {}, userModel, userModelConfig)
//returns
{"whitelist":["1","2","3","4","5","6"]}

and
$.extend(true, {}, userModelConfig, userModel)
"{"whitelist":["a","b","c","4","5","6"]}"
```

As you can see the index position of the array is overwritten rather then extend or merged.

A potential solution would be to transform the arrays into objects, extend them and transform them back.  

I was going to try to fix it and submit a pull request, but i dont have the time tonight so i wanted to get this to you, maybe you have a quicker solution.

**Comment by raymatos** [comment]
Dont have access to push a new branch, was going to fix another issue i found

**Comment by colinskow** [comment]
See line 168 of [config.example.js](https://github.com/colinskow/superlogin/blob/master/config.example.js) for the built-in solution.

Please close if this does what you want it to do.

**Comment by raymatos** [comment]
I am using the config, however extend does not work how it needs to work in order to make this s function correctly.

Adding any valid to the config user model will result in a error stating that username, password and confirm password is not passed.

**Comment by colinskow** [comment]
You shouldn't need to use JQuery extend. Anything you put in the config file under `userModel` is automatically merged into the model.

```js
    if(typeof config.getItem('userModel') === 'object') {
      userModel = extend(true, userModel, config.getItem('userModel'));
    }
```

Please explain specifically what you want to do and include some example code so I can understand your situation.

**Comment by raymatos** [comment]
So what im trying to say is the node extend is basically a clone to jquery extend.  And extend will not merge 2 arrays.

So for example, if you were to add this to the config file

```
userModel: {
    whitelist: [
      'interests',
      'unit',
      'age',
      'subscribe',
      'zipcode'
    ]
  }
```

You would get an error saying the username, password, and confirmPassword is required.  This is because ```userModel = extend(true, userModel, config.getItem('userModel'));``` would return the whitelist array like this

 ```
whitelist: [
      'interests',
      'unit',
      'age',
      'subscribe',
      'zipcode'
    ]
```

This is because extend will overwrite the array rather then merge them.  But what you really want is a unique merge.

Hope that makes more sense.

**Comment by colinskow** [comment]
OK, now I understand exactly what you are saying. Currently if you want to change the `whitelist`, you have to repeat it:

```js
whitelist: [
      'name',
      'username',
      'email',
      'password',
      'confirmPassword',
      ...
    ],
```

I'll work on this for the next version of SuperLogin, but don't know when I'll get to it. If you can do I pull request with a passing test in `user.spec.js` then I would be happy to merge it.
