### ISSUE TITLE
Help with example code

### ISSUE THREAD

**Issue by fariasf** [colinskow/superlogin#2]
Hi! This project sounds really interesting, and I wanted to give it a try.
But when I copied the code from the example, I got this error:

```
Memory Adapter loaded
/var/www/pouch-superlogin/node_modules/superlogin/lib/util.js:99
  Object.keys(providers).forEach(function(provider) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.exports.addProvidersToDesignDoc (/var/www/pouch-superlogin/node_modules/superlogin/lib/util.js:99:10)
    at new module.exports (/var/www/pouch-superlogin/node_modules/superlogin/lib/index.js:51:21)
    at Object.<anonymous> (/var/www/pouch-superlogin/index.js:39:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I tried adding `providers: { local: true }` to the `config` object, and that seemed to work, but the next step (posting to /auth/register) is failing:

```
{ error: 'Validation failed',
  validationErrors: [TypeError: Cannot read property 'match' of undefined],
  status: 400 }
```

So maybe adding `local: true` was not a good idea =)
Could you provide directions on how to get the example code running?

**Comment by fariasf** [comment]
I updated postman and now the user was created!

I think the first part, adding `providers: { local: true }` to the `config` object is still valid (the app won't start without that).

**Comment by colinskow** [comment]
I apologize for releasing without specifically testing the example code first. It was missing `app.use(bodyParser.urlencoded({ extended: false }));` which was causing all requests to be received with a blank body (hence validation errors). The updated version should work as it is now posted.

I fixed the bug that was throwing the error when no providers were specified, and fixed some bugs in the validation code.

**Comment by fariasf** [comment]
Thanks! I'll check the updated code.
BTW I've been playing a bit with this, and so far it is really awesome! Congrats, and thanks for sharing!

**Comment by colinskow** [comment]
The [SuperLogin Demo](https://superlogin-demo.herokuapp.com) is now LIVE! Source code [here](https://github.com/colinskow/superlogin-demo).
