### ISSUE TITLE
Setting loginOnRegistration to true does not return a session

### ISSUE THREAD

**Issue by raymatos** [colinskow/superlogin#20]
setting local.loginOnRegistration: true, does not return a session.

Tested it on your sample app where the issue also exist.

Looks like you are looking for security.loginOnRegistration, however per the docs it should local.loginOnRegistration

**Comment by raymatos** [comment]
Looks like 'loginOnPasswordReset' is also in the wrong namespace

**Comment by colinskow** [comment]
Thank you for letting me know. I will update the docs to show the correct namespace without changing the existing API.

**Comment by colinskow** [comment]
@raymatos: do you want to do a PR for updated docs?

**Comment by raymatos** [comment]
Sure, can you add me as a contributor on the repo.  Also the demo repo so I can fix the config there



—

**Comment by raymatos** [comment]
I guess I should fork it and submit a pull request



—
