### ISSUE TITLE
Calling reset password without a confirm email will result in error

### ISSUE THREAD

**Issue by raymatos** [colinskow/superlogin#21]
Looks like in line 884 of user.js you have

```
return mailer.sendEmail('forgotPassword', user.email, {user: user, req: req, token: user.forgotPassword.token});
```

However if you havent confirm your email yet, then user.email does not exist.

**Comment by raymatos** [comment]
Thinking about this more, if you have ```requireEmailConfirm:false``` then it would make sense to set the user.email at registration.

**Comment by raymatos** [comment]
Well just setting it to email (param passed in) should be fine, since the promise will not resolve if the email doesnt exist in the system.

**Comment by colinskow** [comment]
@raymatos thank you that is a good point. I'll work on this in the next release, replacing `user.email` with `user.email || user.unverifiedEmail.email`.
