### ISSUE TITLE
when there is a '-' in the mail of the user, the DBNAME is unreachable on Cloudant Dashboard.(

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#25]
![image](https://cloud.githubusercontent.com/assets/7273443/12701281/ff3f04ea-c804-11e5-9fd3-0647deca9545.png)

**Comment by colinskow** [comment]
That seems like a quirk in Cloudant. Is it available through the normal HTTP API?

One option would be to escape the "-" character in addition to the others.

**Comment by ronyrun** [comment]
Hey Colin !!!! I wish you a great year!!
Yes :) I know where you do that in your code I'll propose a correction !

Take care

**Comment by ronyrun** [comment]
Yes it is accessible through the normal http api

**Comment by colinskow** [comment]
You may also file an issue with Cloudant, since the "-" character is legal under CouchDB specs.

**Comment by ronyrun** [comment]
Cloudant feedback : 



I can reproduce your problem from our side. Actually you can create databases with "$" or "-" but both cannot be used together when creating databases. We already noticed our developers about this issue, but cannot give an ETA when it is going to be fixed. Apologies for the inconvenience that caused.

**Comment by colinskow** [comment]
@ronyrun good work!

**Comment by ronyrun** [comment]
Cloudant feedback :

Unfortunately, we cannot provide an ETA of when this issue can be resolved. The best option will be not to use the symbols together in a database name.

Regards,
Mercy

--
Mercy Ilade - Cloudant Support

**Comment by colinskow** [comment]
I will modify the code to escape dashes then.

**Comment by ronyrun** [comment]
Great Thank You so much Colin
