### ISSUE TITLE
[how-to?] installation of Redis

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#27]
Hello, 

I have 2 questions concerning Redis

Why using reddit instead of a levelDown PouchDB ?

Is it possible to update the DOC in order to explain how to install Reddit and how to configure it for Superlogin ?

regards,
Ron

**Comment by ssured** [comment]
At the risk of stating something really obvious, but I guess you want to install `redis` not `Reddit`. `apt-get install redis-server` should get you going

**Comment by ronyrun** [comment]
Sorry yes it was REDIS.

**Comment by colinskow** [comment]
See the Redis docs for how to install on your operating system. I used Homebrew on Mac.

For production I used Heroku Redis, which is installed in the Heroku dashboard. I plugin the password using an environment variable.

**Comment by ronyrun** [comment]
OK, I plan to go to heroku.
Do you have a tutorial to build a nodeJS heroku instance ?

**Comment by tohagan** [comment]
- https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by ronyrun** [comment]
thank you @tohagan. 
Thank you for every contribution you made for superlogin.
