### ISSUE TITLE
Downgrade nodemailer@0.7.1

### ISSUE THREAD

**Issue by carlosmbolanos** [colinskow/superlogin#34]
Hello all,

I've been working a little with this awesome plugin and I found an issue with nodemailer, when I try to register a new user with sendConfirmEmail: true I receive:

```
{ cause: [Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it],
  isOperational: true }
```

I managed to solve it by doing so... But I still have the feeling that I'm missing something since by default Superlogin installs Nodemailer@1.4.0. Could you guys give me some clues about it? 

Thanks a lot!

**Comment by cgestes** [comment]
see https://github.com/colinskow/superlogin/pull/31 for a fix

**Comment by carlosmbolanos** [comment]
Thanks @cgestes . 

Should have checked PR before ask
