### ISSUE TITLE
Be able to populate user db with default values

### ISSUE THREAD

**Issue by micky2be** [colinskow/superlogin#36]
When a user register, would be nice to be able to populate the user databases with default values.
Something we could put under model perhaps.

**Comment by cgestes** [comment]
Maybe it can be done by replicating a database to the newly created one.

**Comment by colinskow** [comment]
You may find the [on signup event](https://github.com/colinskow/superlogin/#event-emitter) helpful. The `userDoc` object will tell you what the database is named and you can populate it as you like.

**Comment by colinskow** [comment]
Closing. Feel free to re-open if you have further questions.

**Comment by micky2be** [comment]
I"m using `superlogin.onCreate(fn)`. Works pretty well for what I need.
