### ISSUE TITLE
expose a different url for dbServer

### ISSUE THREAD

**Issue by micky2be** [colinskow/superlogin#37]
The config of the database url on the server (local ip) might differ from the url the client need to access from (public ip).
protocol, host and port could be completely different.

**Comment by colinskow** [comment]
That is a good idea. I will consider adding an option to specify this in the next release.

**Comment by colinskow** [comment]
Done, use `dbServer.publicURL` in the `config` object. This will be available in the next release.

**Comment by micky2be** [comment]
Great. Thank you
