### ISSUE TITLE
Change defaultRoles at runtime

### ISSUE THREAD

**Issue by carlosmbolanos** [colinskow/superlogin#38]
Hi all!

I'm trying to change 'defaultRoles' at runtime usign **superlogin.config.setItem** as indicated on Main API documentation, I printed out the config after change it so I'm sure **setItem** works ok ,but when I'm registering new users it gets the value previously defined on my config file.

```
exports.postUser = function(req, res, next){
  superlogin.config.setItem('security.defaultRoles', [ 'user', 'whatever' ])
  superlogin.createUser(req.body, req)
    .then(function(){
      res.status(201).json({ok: true, success: 'User created'})
    }, function(err){
      res.json(err)
   })
}
```
Any help will be appreciated

**Comment by colinskow** [comment]
Try using [superlogin.onCreate](https://github.com/colinskow/superlogin/#superloginoncreatefn):

```
superlogin.onCreate(function(userDoc, provider) {
  userDoc.roles = [ 'user', 'whatever' ];
  return Promise.resolve(userDoc);
});
```

**Comment by carlosmbolanos** [comment]
It's working now!
Thanks!

**Comment by colinskow** [comment]
You're welcome!
