### ISSUE TITLE
package.json missing "engine" property 

### ISSUE THREAD

**Issue by tohagan** [colinskow/superlogin#39]
Could you please specify a engine constraint in your package.json 

* http://blog.nodejitsu.com/package-dependencies-done-right/

Example: 

       "engine": "node >= 0.4.1"

**Comment by colinskow** [comment]
OK I will definitely do that for the next release, which I hope to get working on in the next few days. I will go over all the pending pull requests and issues.

I'm relatively new to Javascript and this is my first major open source project, so thanks for all your help!

**Comment by tohagan** [comment]
Thanks Colin ... This will really help me to know what node engines to do testing with and for new projects based on this lib .. What engine should select for my projects.

**Comment by tohagan** [comment]
Oh yeah ... If possible (and your dependencies support it!) would be great to use the Node 4.2.x or 4.3.x as they are LTS (long term support).  

https://nodejs.org/en/blog/release/v4.3.0/

**Comment by colinskow** [comment]
Yes, I do my personal testing on 4.x. I believe it will also run on 5.x
without a problem. I will add 4.x to package.json next release.

**Comment by colinskow** [comment]
[Official NPM documentation](https://docs.npmjs.com/files/package.json) specifies "engines" as the correct field.

I am going to add this:

```
"engines" : {
    "node" : ">=4.0.0"
  }
```

It should work on both LTS and latest version, and be tested against both.
