### ISSUE TITLE
failing with `"status\":404,\"name\":\"not_found\",\"message\":\"missing\"`

### ISSUE THREAD

**Issue by rjsteinert** [colinskow/superlogin#40]
Hi there. I'm following the [Quick Start example](https://github.com/colinskow/superlogin#quick-start) in the README but getting the following message. Do you know what the issue could be? I'm running node v4.2.2.

Correction: I just tried the vanilla Quick Start example server code and it worked :+1: . My bad for trying to integrate this first into an existing express server. Now it's time to figure out why I get this message with when using the integrated example code.

<img width="917" alt="screen shot 2016-03-29 at 10 06 20 am" src="https://cloud.githubusercontent.com/assets/156575/14110807/10e392c4-f596-11e5-9df9-5ac9451da99c.png">

**Comment by rjsteinert** [comment]
Setting the Body to raw I get the following.

<img width="913" alt="screen shot 2016-03-29 at 10 11 02 am" src="https://cloud.githubusercontent.com/assets/156575/14110925/a6a6f260-f596-11e5-8d71-0c50c719ae91.png">
<img width="898" alt="screen shot 2016-03-29 at 10 11 16 am" src="https://cloud.githubusercontent.com/assets/156575/14110931/acf01714-f596-11e5-8b40-40f86c9afe6c.png">

**Comment by rjsteinert** [comment]
I'm not sure what it was :P. It's working now. @colinskow Thanks for open sourcing this, looking forward to using it with the Tangerine project http://tangerinecentral.org

**Comment by colinskow** [comment]
You likely didn't have Express `bodyParser` configured correctly.

**Comment by delkant** [comment]
I am having the same issue with v7.6.0

Playing with postman if I try different headers for the Content-Type ( application/x-www-form-urlencoded and application/json) Sometimes it will work, I cannot tell what is the right formula but out of 30 try I got two users registered, I don't know if it has to be with the values on my fields or what. I am getting validation errors at times ( error codes are: 404 and 400 ).

This was working for me for a long time, I don't know if maybe an automatically update of my server on some nodejs components made the difference, but right now I cannot make it to work again (I am glad this is just a test environment :D)

Please advise how to troubleshoot this issue.

**Comment by delkant** [comment]
I wasn't using the latest code and had also some issues to access to some files on my OS, I dont know how I changed this, but it wasn't a superlogin issue on my case.
