### ISSUE TITLE
Does SuperLogin work with a PouchDB server?

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/superlogin#47]
Although the docs hint towards this, I wasn't sure. The reason why I ask is because I am leaning towards the PouchDB-find project for easier in-browser queries compared to the PouchDB views. It sadly only works (for remote instances) with  PouchDB server or CouchDB 2.0 preview. I have decided to use PouchDB server and hence this question.

Thanks in advance!
Sukant

**Comment by colinskow** [comment]
Great question @SukantGujar ... I haven't tested it but it should work. PouchDB-Find also works with Cloudant, which I have tested against extensively with SuperLogin.

**Comment by SukantGujar** [comment]
Okay, I will validate it with PDB-server as well as CouchDB 2.0. WIll let you know how it goes. Cloudant won't work for me as I am looking for a self-hosted CDB :).

**Comment by SukantGujar** [comment]
So here's the result of test specs run against pouchdb-server -

![testresults](https://cloud.githubusercontent.com/assets/6153264/14638793/b02e8aca-0656-11e6-92cf-0161db02b404.png)

As you would notice, only one test fails. Would it cause issues with superlogin?

**Comment by SukantGujar** [comment]
Update - I traced the test in Visual Code and found that pouchdb-server deletes the testkey correctly, but then returns the reason of querying the deleted document as "missing", whereas the test is expecting "deleted". This causes this test to fail.

![testresults](https://cloud.githubusercontent.com/assets/6153264/14639723/be172502-065b-11e6-9b54-8325d638acc2.png)
Still not sure if this check will cause supperlogin to glitch or not. Please comment.

**Comment by colinskow** [comment]
This shouldn't cause any problems in SuperLogin. The issue is that PouchDB-Server is emitting a different reason code than CouchDB. This is safe to ignore for now. I can update the test to check for 'deleted' OR 'missing'.

**Comment by SukantGujar** [comment]
Awesome, thanks!
On Apr 20, 2016 12:35 AM, Colin Skow <notifications@github.com> wrote:This shouldn't cause any problems in SuperLogin. The issue is that PouchDB-Server is emitting a different reason code than CouchDB. This is safe to ignore for now. I can update the test to check for 'deleted' OR 'missing'.
