### ISSUE TITLE
Adding an endpoint like 'validSession'

### ISSUE THREAD

**Issue by micky2be** [colinskow/superlogin#53]
When reloading my SPA I need to know for sure that my current session (in local storage) is still valid.

I'm going through `refresh` for now, but ideally I would like to avoid writing in the database just for that.
But the idea would be really similar and could even trigger a `login` event on the frontend.

**Comment by colinskow** [comment]
Send a get request to `/session` and it will reply with the session information if valid. Otherwise you will get a 401.

**Comment by colinskow** [comment]
@TODO: document `/session` endpoint.

**Comment by micky2be** [comment]
Why I didn't think about that?
Thank you.
