### ISSUE TITLE
SuperLogin ForgotPassword UseCase - Reset Pasword Link for an hybrid mobile App.

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#55]
Hello, 

## I try to implement the ForgotPAssword UseCase on a Cordova / PhoneGap / Ionic Mobile Hybrid App.
I need to manage the password reset from that and not from a website...

I launch the command : 
```
superlogin.forgotPassword("MyEmail@mail.com");
```
And I receive a proper email : 
![image](https://cloud.githubusercontent.com/assets/7273443/14766542/c2cd01fa-0a0e-11e6-9a85-7ad5cf2afcc1.png)

When I click on the link : 
I got this error : `Cannot GET /password-reset/mK9671GeQKWOo74U4Y6MIw`

and from the Heroku Logs : 
```
2016-04-24T09:18:20.356789+00:00 heroku[router]: at=info method=GET path="/password-reset/mK9671GeQKWOo74U4Y6MIw" host=*******-superlogin.herokuapp.com request_id=8a4be95f
-699a-4abc-af19-41da2f0022a1 fwd="78.***.***.64" dyno=web.1 connect=0ms service=2ms status=404 bytes=427
```

# How Can I make this working properly ?

I can see on the Superlogin-demo the same e-mail with this link : 

## On the superlogin Demo there is a Sensegrid redirection like : 
![image](https://cloud.githubusercontent.com/assets/7273443/14769307/84cb4a86-0a56-11e6-8f54-5ecd77d55c67.png)

```
https://u19**480.ct.sendgrid.net/wf/click?upn=4RVtDsLk14tpYYyLSbT246p1i9JuyL69W3GiHHUdnVKuej6uxOSagz5XJ-2Ff7-2FHnwif3PaOVAz6M1xcMFA9-2Fnhl5hPrHL616COgWtIw_BQvb1-2B8lEcvg1yJWswS37EQzdeiO5rjciTkF5tMolWwvOW0rYeC9leKCRGNN7toZFCHQvphEzfXwnqq6QZFIRLku0kYTN-2F7pfIZqFk1HoRhzLnGgcoeZPPMEGIidjl-2FA5B2rJUZQzXcjHUfgcILtMYrtiGU6ROx6rYrjDjc-2Bg-2B-2FPHSNN6ssq7xDB1C4tejBm-2F12cUPN6f-2F-2FpnnsHk5P13Q-3D-3D
```
This link redirect to the superlogin-demo 

What Can I do in my context ? 
**[Mobile hybrid App] => [Email with Reset Link] => [form hybrid App] is not possible.**

Is this workflow a good one ?

Like something with a code pin : 
1) "Click Forgot Pwd Button" 
2) "An email is sent with a CODE PIN" 
3) "The user can type a Form on the app with 
- a code pin
- his email
- new password
- confirm new password.

**Comment by colinskow** [comment]
Since you are using a hybrid app there is no way to link to it externally. I recommend creating a simple webpage with Javascript that processes the password reset. It will be outside your app, but as soon as the password is reset in a web browser the new password will work inside your app. Just copy the code from `SuperLogin Demo`.

To accomplish this you can customize the 'forgot password' email template. See `config.example.js` for instructions.

**Comment by ronyrun** [comment]
hi Colin, 

Thank you.
I don't understand how you manage to redirect the mail link from your demo with Sensegrid...
On my side I use a XOAuth2 from Gmail.
and I only get that :  Cannot GET /password-reset/mK9671GeQKWOo74U4Y6MIw

Do you have any info to help me on that ?
