### ISSUE TITLE
Registration Down

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#6]
![image](https://cloud.githubusercontent.com/assets/7273443/9913750/a7bed50e-5cae-11e5-996d-2d37029406aa.png)

**Comment by ronyrun** [comment]
![image](https://cloud.githubusercontent.com/assets/7273443/9913859/39cf0dba-5caf-11e5-90e7-652de7d03d1c.png)

**Comment by colinskow** [comment]
That's what happens when I rush out a release without thoroughly testing. NPM update and it should be fixed.
