### ISSUE TITLE
Cookie/Header based authentication of userDBs

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/superlogin#61]
Hi,

Currently the util.getDBURL API injects username and password into the private DB URLs. Is there a way to use session tokens for authorization instead of this? I understand that in Production, the Superlogin server will be behind SSL, but if there's an alternative, it'd be great.

Thanks!

**Comment by colinskow** [comment]
The `getDBURL` API injects the session token and a randomly generated password into the database URL. The user's login information is not sent. When the session is closed this will no longer work. Regardless, any production system that is not behind SSL is insecure.

**Comment by SukantGujar** [comment]
Thanks for your response Colin. I looked into the code for getDBUrl and it seems to simply append URI encoded `dbServer.user` and `dbServer.password` from the configuration settings. Could you please point me to the code where it generates and uses random password for `getDBUrl`?
Here's what it looks to me -> 
In dbAuth/index.js/this.authorizeUserSessions -
`var db = new PouchDB(util.getDBURL(config.getItem('dbServer')) + '/' + personalDB);`
And then in util.getDBURL -
`url = db.protocol + encodeURIComponent(db.user) + ':' + encodeURIComponent(db.password) + '@' + db.host;`
Am I looking at the wrong method?

**Comment by colinskow** [comment]
See [here](https://github.com/colinskow/superlogin/blob/master/lib/user.js#L1198) for the code that generates this. Username and password are a URL Safe UUID.

**Comment by SukantGujar** [comment]
Thanks Colin, I am closing this issue.
