### ISSUE TITLE
forgotPassword() should secure hash the stored token.

### ISSUE THREAD

**Issue by tohagan** [colinskow/superlogin#67]
If an attacker broke into your SL user database, they can use `<any-user>.forgotPassword.token` to change passwords on all non-expired tokens. They are as good as plain-text passwords. The tokens should be secure hashed prior to storage in the database and of course verified using the same hash algorithm.

I realised this after reading this excellent checklist that I'd recommend:

- http://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication

**Comment by tohagan** [comment]
You'd also need to provide a db migration for existing users.

**Comment by colinskow** [comment]
I welcome a PR. No need to do db migration. We just discard all existing reset password tokens.

**Comment by tohagan** [comment]
Yeah ... Worst case I guessed they'd just expire anyway.
