### ISSUE TITLE
Weak unit tests for EventEmitter.emit() calls. 

### ISSUE THREAD

**Issue by tohagan** [colinskow/superlogin#69]
This code pattern is frequently used to unit test event emits(). I'm seeing lots of them in user.spec.js.
However this is a weak test constraint as all it test is that **if** an event **is** emitted it will have a user with given `user._id` value. However, it does not check that the event ever actually happened!

```
    var emitterPromise = new BPromise(function(resolve) {
      emitter.once('signup', function(user) {
        expect(user._id).to.equal('superuser');
        resolve();
      });
    });
```

A better approach would be to either use a `spy()` to watch for `emit()` calls or to create a `MockEventEmitter` class that can record the `emit()` calls. 

I'm currently in the process of capturing calls to `Mailer` and so I've just created a `MockMailer` class that does the same kind of thing ...

```
// MockMailer to capture sendEmail() calls
module.exports = function(config) {

  this.reset();
  
  this.reset = function() {
    this.calls = [];
  };

  this.sendEmail = function(templateName, email, locals) {
    this.calls.push({
      templateName: templateName,
      email: email,
      locals: locals
    });
  }
}
```

Now I can easily assert the calls ...

```
     var mailer = new MockMailer(userConfig);
     var emitter = new MockEventEmitter();
     var user = new User(userConfig, userDB, keysDB, mailer, emitter);

     before(function() {
          mailer.reset();
          emitter.reset();
     });

     ....
        expect(mailer.calls.length).to.be(1);
        expect(mailer.calls[0].templateName).to.be('forgotPassword');
        expect(mailer.calls[0].email).to.be(testUserForm.email);
        expect(mailer.calls[0].locals.user.username).to.be(testUserForm.username);
        expect(mailer.calls[0].locals.token).to.be.a('string');
        resetToken = mailer.calls[0].locals.token;  // token sent to user

        expect(emitter.calls.length).to.be(1);
        expect(emitter.calls[0].user).to.be.an('object');
        expect(emitter.calls[0].user._id).to.equal('superuser');

```

**Comment by tohagan** [comment]
You could also use a `spy()` ...  Not sure if you can assert objects in call args.

- https://github.com/mochajs/mocha/wiki/Spies

**Comment by colinskow** [comment]
I realize my tests are weak in many areas and want to improve them. I welcome any PRs in this area.

If the event doesn't happen then the test will time out and fail. The test does work, but I'm not sure if it is obvious what happened from the error message.

**Comment by tohagan** [comment]
oh ok. Sorry if missed that.
