### ISSUE TITLE
dbServer.userDB is Public

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#7]
At launch, the dbServer.userDB doesn't have any security.

dbServer.user should be the only account to access it.

**Comment by colinskow** [comment]
It is your responsibility to protect it with the correct CouchDB configuration. You need to push your own design doc with `validate_doc_update`. You can access `superlogin.userDB` and seed your validate function on startup.

**Comment by ronyrun** [comment]
OK
