### ISSUE TITLE
Question: Difference between /auth/{provider} and /auth/link/{provider}

### ISSUE THREAD

**Issue by HendrikRoth** [colinskow/superlogin#77]
Hello - i am still trying to integrate paypal to my application. /auth/{provider} works fine - but /auth/link/{provider}?bearer_token={session.token}:{session.password} results for me in

```
data: '{"error_description":"redirect uri mismatch between auth code and token","error":"invalid_request","correlation_id":"","information_link":"https://developer.paypal.com/docs/api/#errors"}' 
```

in the paypal backend i set the redirect uris to:

http://127.0.0.1:4000/auth/paypal/callback
and
http://127.0.0.1:4000/auth/link/paypal/callback

did i miss something? Where is internally the difference in the call? (i know it is to link the provider to an existing account)

**Comment by colinskow** [comment]
I have tested against Facebook, Google, LinkedIn, Github and WindowsLive. I have not tested SuperLogin against Paypal so it may have quirks.

You need to add `http://127.0.0.1:4000/auth/link/paypal/callback` to your list of valid callback URLs in your dashboard and that should solve it.

**Comment by HendrikRoth** [comment]
Hm did this resulting the error

**Comment by colinskow** [comment]
In your config, try setting `providers.paypal.stateRequired` to `true` and see if that makes a difference. That is how I solved Google and LinkedIn. If it works I will make that mode default for Paypal on future releases of SuperLogin.

Also make sure you are using Paypal's Oauth2 strategy since Oauth1 is not supported.

**Comment by HendrikRoth** [comment]
This worked, thanks!

**Comment by HendrikRoth** [comment]
your example config file has the wrong property for this mentioned. 

https://github.com/colinskow/superlogin/blob/master/config.example.js#L166

stateRequired works, requireState not

**Comment by colinskow** [comment]
Thanks for spotting that... fixed!
