### ISSUE TITLE
Check if CouchDB is connected

### ISSUE THREAD

**Issue by quanglam2807** [colinskow/superlogin#8]
I tried to connect my project with Cloudant with this code

```
  dbServer: {
    protocol: "https://",
    host: "cloudant_account.cloudant.com/_all_dbs",
    user: "cloudant_account",
    password:  CLOUDANT_ACCOUNT_PASSWORD,
    cloudant: true,
    userDB: "sl-users",
    couchAuthDB: "_users"
  }
```
But I think it doesn't work as the APIs don't work properly. Is there anyway for me to check if CouchDB is connected? Do you think it will be better if we can add a log for it? Also, if I made something wrong with my configurations, please help me!

**Comment by quanglam2807** [comment]
Finally, I make it work! 
```
host: "cloudant_account.cloudant.com/_all_dbs",
```
to
```
host: "cloudant_account.cloudant.com",
```

Still, I think we need to add log for this.

**Comment by colinskow** [comment]
Yes, `host` must be set to the root of your CouchDB or Cloudant server, not `/_all_dbs`. SuperLogin won't actually try to connect to the DB until you attempt to perform an actions such as login or registration. If it cannot connect, it should throw an error the first action you try to perform.

Any errors thrown will go to `console.error` so you should be able to use a logger like `morgan` to capture these.

If you have any specific suggestions for how to improve this, let me know.

**Comment by colinskow** [comment]
OK, I did confirm that when the DB connection fails, the API seems to wait forever and gives no error. This is because there is no timeout set on PouchDB. I'll add a feature in the next release so you can set your own personal timeout, and you should get a correct error after that.

**Comment by colinskow** [comment]
Apparently, if a Node.js request is unable to connect to the server, then the [timeout](https://github.com/request/request#requestoptions-callback) is set by your operating system (generally between 20 and 120 seconds) and there is no easy way to override it. So unfortunately if your DB is configured wrong or isn't responding, then the SuperLogin API is going to hang for a while. I don't think there's much we can do about it.

**Comment by colinskow** [comment]
OK, I fixed a bug in the `/login` code, which was preventing the promise from correctly rejecting. It will now display the error: `Error: connect ECONNREFUSED 127.0.0.1:5984` if unable to connect. I will upload this fix with the next release shortly.
