### ISSUE TITLE
[Google Passport strategy Q] Not getting an access_Token anymore - idToken and serverAuthCode 

### ISSUE THREAD

**Issue by ronyrun** [colinskow/superlogin#80]
Hello, 
On my Ionic app, I use the cordova-plugin-googleplus, with the last version :
Instead of getting an access_token (oauthToken) we now get an idToken and serverAuthCode.

Some people told me that serverAuthCode was the new access_token but when trying on my app with : 
`var GoogleTokenStrategy = require('passport-google-token').Strategy;`

I now get an Unauthorized error.
Does anyone has a method to deal with  idToken and serverAuthCode on SuperLogin ?

**Comment by ronyrun** [comment]
Got the oauthToken from the client device.

**Comment by sam2x** [comment]
Hey got also an "unauthorized error", did you solve this ? can you share your feedback ? thx.
