### ISSUE TITLE
User registration stores user when sending mail fails

### ISSUE THREAD

**Issue by peteruithoven** [colinskow/superlogin#88]
I'm still figuring out how to use gmail for sending E-mails but because of that I notived that users are also created / stored when sending the E-mail fails. For example when the E-mail service username or password is incorrect.

**Comment by colinskow** [comment]
Yes, this is intentional. I didn't want to block registration because of an error in the email system. I am going to implement functionality soon for an admin to resend the verification email.

Ideally SuperLogin would store a queue of unsuccessful emails to retry later.

**Comment by peteruithoven** [comment]
Sounds like a good solution. With that last part it wouldn't even require an action from the user. 
Pressing a resend button would also be another easy method to check if the E-mail sending works.
