### ISSUE TITLE
Optional User Middleware

### ISSUE THREAD

**Issue by HendrikRoth** [colinskow/superlogin#92]
I am missing an optional user middleware. Just for checking in specific routes, a user is logged in or not.

requireAuth blocks the whole request for guest users.

what do you think?

**Comment by colinskow** [comment]
If authentication is optional you can check `req.user` to get user information in case the request is authenticated. Otherwise it will be undefined.

**Comment by HendrikRoth** [comment]
Oh ok, thanks.
