### ISSUE TITLE
TypeError: superlogin.onLink is not a function

### ISSUE THREAD

**Issue by peteruithoven** [colinskow/superlogin#96]
onLink is mentioned in the readme:
https://github.com/colinskow/superlogin#superloginonlinkfn

But it doesn't seem to exist anymore? 

Is there another handler that's called after linking? Or is onCreate now also called?

**Comment by colinskow** [comment]
You are correct. The function exists, but the main API doesn't expose it. Thank you for pointing this out. This will be fixed in the next release.

**Comment by allansduarte** [comment]
Hello. Is there a forecast for a version?
